services:
  web:
    build:
      context: .
      target: runner              # build the minimal runtime image
    env_file:
      - .env.production           # runtime-only envs for the server
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      HOSTNAME: 0.0.0.0
      PORT: "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped
  